package com.aerixa.app.application.configuration.audit;

public enum ConfigurationAuditEntityType {
    ESTABLISHMENT,
    ENTRY_DIPLOMA,
    ACADEMIC_LEVEL,
    PROGRAM_TRACK,
    PROGRAM_TRACK_LEVEL,
    ACQUISITION_CHANNEL,
    FUNNEL_STAGE,
    FUNNEL_STAGE_TRANSITION,
    USER_PIPELINE_VIEW_PREFERENCE,
    INTAKE_PERIOD,
    CANDIDATE,
    CANDIDATE_APPLICATION,
    CANDIDATE_NOTE,
    CANDIDATE_NOTE_ATTACHMENT,
    ESTABLISHMENT_WHATSAPP_CONFIG,
    CANDIDATE_CONVERSATION,
    CANDIDATE_CONVERSATION_MESSAGE
}
