-- V1.18__add_mail_type_category.sql
-- Ajout de la categorie fonctionnelle sur les types de mail

ALTER TABLE auth.mail_types
    ADD COLUMN category VARCHAR(100);

UPDATE auth.mail_types
SET category = CASE code
    WHEN 'PASSWORD_RESET' THEN 'AUTH_PASSWORD_RESET'
    WHEN 'EMAIL_VERIFICATION' THEN 'AUTH_EMAIL_VERIFICATION'
    WHEN 'RESEND_EMAIL_VERIFICATION' THEN 'AUTH_RESEND_EMAIL_VERIFICATION'
    WHEN 'ACCOUNT_CREATED_INITIAL_PASSWORD' THEN 'AUTH_ACCOUNT_CREATED_INITIAL_PASSWORD'
    WHEN 'USER_INVITATION' THEN 'AUTH_ACCOUNT_CREATED_INITIAL_PASSWORD'
    WHEN 'WELCOME_EMAIL' THEN 'SYSTEM_NOTIFICATION'
    WHEN 'ACCOUNT_ACTION_REMINDER' THEN 'ACCOUNT_ACTION_REMINDER'
    WHEN 'ACCOUNT_SUSPENDED' THEN 'ACCOUNT_SUSPENDED'
    WHEN 'ACCOUNT_REACTIVATED' THEN 'ACCOUNT_REACTIVATED'
    WHEN 'SYSTEM_NOTIFICATION' THEN 'SYSTEM_NOTIFICATION'
    ELSE UPPER(code)
END
WHERE category IS NULL;

ALTER TABLE auth.mail_types
    ALTER COLUMN category SET NOT NULL;

CREATE UNIQUE INDEX idx_mail_type_category ON auth.mail_types(category);
